### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by belak** [evalphobia/logrus_sentry#14]
Right now there isn't a LICENSE file, so it's unclear what this is actually licensed under.

**Comment by evalphobia** [comment]
@belak 
Since [Sirupsen/logrus](https://github.com/Sirupsen/logrus) use MIT license, so I'll add the LICENSE file of MIT.

Any thougts?

/cc @gigaroby

**Comment by gigaroby** [comment]
LGTM

**Comment by belak** [comment]
I'm not particularly picky about the license, just that it has one. :)
