### ISSUE TITLE
Add support for go-raven Environment and Release 

### ISSUE THREAD

**Issue by medzin** [evalphobia/logrus_sentry#22]
Please add ability to configure go-raven client's `Environment` and `Release`, so they will be sent to Sentry. Now, you can't distinguish an events of a different versions of application or different runtime environments.

**Comment by evalphobia** [comment]
Thanks @medzin 🍣 

- SetEnvironment()
- SetRelease()
 
are supported in [v0.2.6](https://github.com/evalphobia/logrus_sentry/releases/tag/v0.2.6) :)
