### ISSUE TITLE
case-insensitive import collision

### ISSUE THREAD

**Issue by viru** [evalphobia/logrus_sentry#36]
As per https://github.com/sirupsen/logrus/issues/451#issuecomment-264332021 logrus import path should be uppercase again.

**Comment by evalphobia** [comment]
@bsphere @viru 
Thank you guys letting me know it.
 
I reverted the package name and back again now.
Sorry for the confusing 😭

**Comment by shuLhan** [comment]
And they change (and recommend) it to use lowercase again: https://github.com/sirupsen/logrus/issues/543

Can we open the issue again?
